# Copyright 2021 Eric Fedosejevs
#

include(${UTILOGENY_DIR}/cmake/find_install_package.cmake)
include(${UTILOGENY_DIR}/cmake/target_deploy_lib.cmake)

option(ENABLE_SDL2 "Enable SDL2" ON)
option(ENABLE_SDL2_MIXER "Enable audio support using SDL2_mixer" ON)
option(ENABLE_SDL2_IMAGE "Enable image support using SDL2_image" ON)

macro(check_sdl_settings)
	if(ENABLE_SDL2_MIXER AND NOT ENABLE_SDL2)
		message(FATAL_ERROR "Cannot enable SDL2 mixer without enabling SDL2!")
	endif()

	if(ENABLE_SDL2_IMAGE AND NOT ENABLE_SDL2)
		message(FATAL_ERROR "Cannot enable SDL2 image without enabling SDL2!")
	endif()
endmacro()

function(target_include_sdl2 target)
	check_sdl_settings()
	set(SDL2_BUILDING_LIBRARY 1) # Omit SDL main()
	if(ENABLE_SDL2)
		message("Trying to include SDL2")
		if(TARGET "SDL2::SDL2")
			message("SDL2 target already added.")
		endif()
		find_install_package(PACKAGE_NAME "SDL2" VCPKG_NAME "sdl2" REQUIRED_TARGETS "SDL2::SDL2")
		target_include_lib(LINK_TARGET ${target} PACKAGE_NAME "SDL2")
	endif()
	if(ENABLE_SDL2_MIXER)
		find_install_package(PACKAGE_NAME "SDL2_mixer" VCPKG_NAME "sdl2-mixer" REQUIRED_TARGETS "SDL2_mixer::SDL2_mixer" INCLUDES_NOT_REQUIRED)		
		target_include_lib(LINK_TARGET ${target} PACKAGE_NAME "SDL2_mixer")
	endif()
	if(ENABLE_SDL2_IMAGE)
		find_install_package(PACKAGE_NAME "sdl2-image" VCPKG_NAME "sdl2-image" REQUIRED_TARGETS "SDL2::SDL2_image" INCLUDES_NOT_REQUIRED)
		target_include_lib(LINK_TARGET ${target} PACKAGE_NAME "sdl2-image")
	endif()
endfunction()

function(target_link_sdl2 target)
	check_sdl_settings()
	target_include_sdl2(${target})

	get_target_property(SDL_IMPORTED_LOCATION_RELEASE SDL2::SDL2 IMPORTED_LOCATION_RELEASE)
	get_target_property(SDL_IMPORTED_IMPLIB_RELEASE SDL2::SDL2 IMPORTED_IMPLIB_RELEASE)
	get_target_property(SDL_IMPORTED_LOCATION_DEBUG SDL2::SDL2 IMPORTED_LOCATION_DEBUG)
	get_target_property(SDL_IMPORTED_IMPLIB_DEBUG SDL2::SDL2 IMPORTED_IMPLIB_DEBUG)

	message(STATUS "SDL_IMPORTED_LOCATION_RELEASE:${SDL_IMPORTED_LOCATION_RELEASE}")
	message(STATUS "SDL_IMPORTED_IMPLIB_RELEASE:${SDL_IMPORTED_IMPLIB_RELEASE}")
	message(STATUS "SDL_IMPORTED_LOCATION_DEBUG:${SDL_IMPORTED_LOCATION_DEBUG}")
	message(STATUS "SDL_IMPORTED_IMPLIB_DEBUG:${SDL_IMPORTED_IMPLIB_DEBUG}")
	
	message(STATUS "SDL_IMPORTED_LOCATION_DEBUG:${SDL_IMPORTED_LOCATION_DEBUG}")
	message(STATUS "SDL_IMPORTED_IMPLIB_DEBUG:${SDL_IMPORTED_IMPLIB_DEBUG}")

	if(ENABLE_SDL2)
		target_link_deploy_lib(LINK_TARGET ${target} PACKAGE_NAME "SDL2")
	endif()
	if(ENABLE_SDL2_MIXER)
		target_link_deploy_lib(LINK_TARGET ${target} PACKAGE_NAME "SDL2_mixer")
	endif()	
	if(ENABLE_SDL2_IMAGE)
		target_link_deploy_lib(LINK_TARGET ${target} PACKAGE_NAME "sdl2-image")
	endif()
endfunction()